global:
  scrape_interval: 15s       # coleta m√©tricas a cada 15 segundos
  evaluation_interval: 15s   # avalia regras de alertas a cada 15 segundos
  external_labels:
    project: "petr4-lstm-api"
    environment: "production"

scrape_configs:
  - job_name: "petr4-lstm-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: "prometheus-self"
    static_configs:
      - targets: ["localhost:9090"]
